### ISSUE TITLE
[Feat] 탭바 뷰와 세계시계 뷰 구현

### ISSUE THREAD

**Issue by zyeongPark** [SwiftDiggingClub/iClone_Clock#4]
## ✏️ Summary

시계 앱의 탭바를 구현하고, world Clock 부분 뷰만 구현합니다. 

<br>

## ✨ Description

"뷰 구현하기"
시계 앱의 탭바 뷰를 구현하고,
탭 별 상세 뷰는 world Clock만 구현합니다. 
<br>

## ✓ Todo
- [ ] 시계 앱 탭 뷰 구현 
- [ ] world Clock 제목 구현 
- [ ] 상위 탭 구현 : Edit, +, WorldClock 
- [ ] 서울 시각을 시계앱의 기본으로 구현 

<br>

## 🗒️ Note (optional)

화이팅 스위프트 디깅 클럽!!
