### ISSUE TITLE
[Feat] 스톱워치 구현

### ISSUE THREAD

**Issue by moonkey48** [SwiftDiggingClub/iClone_Clock#7]
## ✏️ Summary

시계앱에서 스톱워치 탭을 구현한다. 

<br>

## ✨ Description

<br>

## ✓ Todo
- [ ] 스톱워치 기본 UI 구현
- [ ] 스톱워치 시작 및 준단 기능 구현
- [ ] 스톱워치 재설정 기능 구현
- [ ] 스톱워치 랩 기능 구현

<br>
